export type Lang = 'tr' | 'en';
export type Entry = {id:string; tr:string; en:string; descTr:string; descEn:string; soon:boolean; image?:string; price?:string};
export type Content = {headlineTr:string; headlineEn:string; introTr:string; introEn:string; aboutTr:string; aboutEn:string; phone:string; whatsapp:string; instagram:string; location:string; heroImage:string; services:Entry[]; products:Entry[]};
const entry=(id:string,tr:string,en:string,descTr:string,descEn:string,soon=false):Entry=>({id,tr,en,descTr,descEn,soon});
export const initialContent:Content={
headlineTr:'Türkiye için\ntarım çözümleri.',headlineEn:'Agricultural solutions\nfor Türkiye.',
introTr:'Doğru bilgi, güçlü ekipman ve modern üretim çözümleri. Siirt’ten Türkiye’nin her yerine, tarımın her aşamasında yanınızdayız.',introEn:'Practical expertise, reliable equipment and modern growing solutions. Supporting every stage of agriculture from Siirt across Türkiye.',
aboutTr:'2026 yılında Siirt’te kurulan OKUR AGRO, üreticinin ihtiyaç duyduğu bilgi, ürün ve teknolojiyi bir araya getirir. Amacımız; modern tarım uygulamalarıyla verimliliği, ürün kalitesini ve üreticinin kazanç potansiyelini geliştirmektir. Küçük üreticiden büyük tarım işletmelerine kadar, üretimin her aşamasında ulaşılabilir destek sunuyoruz.',aboutEn:'Founded in Siirt in 2026, OKUR AGRO brings together the knowledge, products and technology growers need. We aim to improve productivity, crop quality and earning potential through modern agricultural practices. From small growers to large agricultural businesses, we provide accessible support throughout production.',phone:'905461166424',whatsapp:'905461166424',instagram:'okuragro',location:'Siirt',heroImage:'/fields.jpg',
services:[entry('danismanlik','Tarım danışmanlığı','Agricultural consulting','Zirai personel desteği, bağ ve bahçe kontrolleri, üretim sürecine uygun bakım ve bitki koruma yönlendirmesi.','Agricultural staff support, orchard and vineyard monitoring, and guidance on crop care and protection.'),entry('salep','Salep yetiştiriciliği','Salep cultivation','Salep üretimi, fide ve yumru satışı, yetiştiricilik danışmanlığı. Üretim planlamasından bakıma kadar yanınızdayız.','Salep production, seedling and tuber sales, and cultivation consulting, from production planning to crop care.'),entry('topraksiz','Topraksız tarım','Soilless agriculture','Hidroponik ve cocopeat sistemleriyle kontrollü üretim. İhtiyacınıza uygun sistemler için bizimle görüşün.','Controlled growing with hydroponic and cocopeat systems. Talk to us about solutions for your production needs.'),entry('ekipman','Tarım ekipmanları','Farm equipment','Traktör, pulluk, kültivatör ve römork dahil tarımsal faaliyetlere uygun ekipman tedariki.','Equipment supply for agricultural operations, including tractors, ploughs, cultivators and trailers.'),entry('bitki','Bitkisel üretim çözümleri','Crop production solutions','Tohum, fide, gübre ve zirai ilaç ihtiyaçlarınız için ürün tedariki ve seçim desteği.','Supply and selection support for seeds, seedlings, fertilisers and crop protection products.'),entry('aromatik','Safran & aromatik bitkiler','Saffron & aromatic plants','Safran, lavanta, kekik ve biberiye gibi katma değerli bitkilerde üretim, satış ve danışmanlık.','Production, sales and consulting for value-added crops including saffron, lavender, thyme and rosemary.'),entry('drone','Zirai drone','Agricultural drones','Drone satışı, ilaçlama ve gübreleme hizmetleri için hazırlıklarımız sürüyor.','Drone sales, crop spraying and fertilisation services are in preparation.',true)],
products:[entry('salep-urun','Salep fide & yumru','Salep seedlings & tubers','Yetiştiricilik hedefinize uygun salep materyalleri hakkında bilgi alın.','Ask about salep growing material for your production plans.'),entry('tohum','Tohum & fide','Seeds & seedlings','Sebze ve meyve üretimine yönelik tohum ve fide seçenekleri.','Seed and seedling options for fruit and vegetable production.'),entry('gubre','Gübre','Fertilisers','Üretiminizin ihtiyaçlarına uygun doğal ve suni gübre seçenekleri.','Natural and mineral fertiliser options for your production needs.'),entry('zirai-ilac','Zirai ilaçlar','Crop protection','Ürününüz ve ihtiyacınız için uygun seçenekleri ekibimizle değerlendirin.','Discuss suitable options for your crop and requirements with our team.'),entry('makine','Makine & ekipman','Machinery & equipment','Traktör, toprak işleme ekipmanları ve römork seçenekleri.','Tractors, tillage equipment and trailers.'),entry('aromatik-urun','Safran & aromatikler','Saffron & aromatics','Safran ve tıbbi-aromatik bitki seçenekleri için iletişime geçin.','Contact us for saffron and medicinal and aromatic plant options.')]
};
