'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowDown,Phone,Menu,X,MoveUpRight,Sprout,Tractor,Leaf,ScanLine,Wind,MapPin} from 'lucide-react';
import ServiceInformation from './service-information';
import type {Content,Lang} from './content';
export function Logo(){return <span className="logo"><img className="brand-logo" src="/okur-agro-logo.webp" alt="OKUR AGRO — Geleceği Topraktan Üretiyoruz." width={1448} height={1086}/></span>}
export default function Site({content:c,initialLang='tr',detail,children,pagePath}:{content:Content;initialLang?:Lang;detail?:string;children?:React.ReactNode;pagePath?:string}){
const [menu,setMenu]=useState(false);const lang=initialLang,en=lang==='en';const t=(tr:string,eng:string)=>en?eng:tr;
useEffect(()=>{document.documentElement.lang=lang;},[lang]);
useEffect(()=>{const nodes=document.querySelectorAll('.reveal');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('shown');obs.unobserve(e.target)}}),{threshold:.08});nodes.forEach(n=>{n.classList.add('observe');obs.observe(n)});return()=>obs.disconnect()},[lang,detail]);
const wa=(subject='')=>`https://wa.me/${c.whatsapp}?text=${encodeURIComponent(t('Merhaba, '+subject+' hakkında bilgi almak istiyorum.','Hello, I would like information about '+(subject||'your services')+'.'))}`;
const item=c.services.find(s=>s.id===detail);const home=en?'/en':'/';const nav=[['hakkimizda',t('Hakkımızda','About')],['hizmetler',t('Çözümlerimiz','Solutions')],['urunler',t('Ürünler','Products')],['iletisim',t('İletişim','Contact')]];
return <><header className="header"><a href={home} aria-label="OKUR AGRO"><Logo/></a><nav className={menu?'nav open':'nav'}>{nav.map(([id,label])=><a key={id} href={id==='hizmetler'||id==='urunler'?`${home}#${id}`:`${en?'/en':''}/${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="header-right"><a className="language" href={en?(detail?'/cozumler/'+detail:pagePath||'/'):(detail?'/en/cozumler/'+detail:'/en'+(pagePath||''))} aria-label={en?'Türkçe':'English'}>{en?'EN / TR':'TR / EN'}</a><a className="header-call" href={`tel:+${c.phone}`}>{t('Bize ulaşın','Contact us')} <ArrowUpRight size={17}/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={t('Menüyü aç/kapat','Toggle menu')} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
{children?children:item?<main><section className="detail-hero"><a href={`${home}#hizmetler`}>← {t('Tüm çözümler','All solutions')}</a><p className="eyebrow">OKUR AGRO / {t('ÇÖZÜMLERİMİZ','OUR SOLUTIONS')}</p><h1>{en?item.en:item.tr}</h1>{item.soon&&<span className="badge">{t('Yakında','Coming soon')}</span>}<p>{en?item.descEn:item.descTr}</p><a className="button green" href={wa(en?item.en:item.tr)} target="_blank" rel="noreferrer">{t('WhatsApp’tan bilgi alın','Enquire on WhatsApp')}<ArrowUpRight/></a></section><section className="section detail-body"><div><p className="eyebrow">{t('ÜRETİMİNİZ İÇİN','FOR YOUR PRODUCTION')}</p><h2>{t('Birlikte doğru\nadımı atalım.','Let’s find your\nnext step.')}</h2></div><div><p>{t('Üretim alanınızı, yetiştirdiğiniz ürünü ve ihtiyacınızı bize anlatın. Bölgenize ve üretim hedeflerinize uygun seçenekleri birlikte değerlendirelim.','Tell us about your growing area, crops and requirements. Together, we can consider options that suit your region and production goals.')}</p><a className="text-link" href={`tel:+${c.phone}`}>{t('Ekibimizle görüşün','Speak to our team')} <ArrowUpRight/></a></div></section><ServiceInformation id={item.id} en={en}/></main>:<main>
<section className="hero"><img className="hero-image" src={c.heroImage==='/fields.jpg'?'/fields-1600.webp':c.heroImage} srcSet={c.heroImage==='/fields.jpg'?'/fields-800.webp 800w, /fields-1600.webp 1600w, /fields-2400.webp 2400w':undefined} sizes="100vw" fetchPriority="high" alt={t('Yeşil tarım arazilerinin havadan görünümü','Aerial view of green agricultural fields')}/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light"><span className="live-dot"/>{t('GELECEĞİ TOPRAKTAN ÜRETİYORUZ.','WE GROW THE FUTURE FROM THE SOIL.')}</div><h1>{en?c.headlineEn:c.headlineTr}</h1><p>{en?c.introEn:c.introTr}</p><div className="hero-actions"><a className="button green" href="#hizmetler">{t('İhtiyacınıza uygun çözümü bulun','Find your growing solution')}<ArrowUpRight/></a><a className="hero-phone" href={`tel:+${c.phone}`}><Phone size={18}/>{t('Birlikte konuşalım','Let’s talk')}</a></div></div><div className="hero-bottom"><span><MapPin size={16}/> SİİRT · {t('TÜRKİYE GENELİ HİZMET','SERVING TÜRKİYE')}</span><a href="#hakkimizda">{t('Keşfetmek için kaydırın','Scroll to explore')}<ArrowDown size={18}/></a></div><span className="hero-side">AGRICULTURE. REIMAGINED.</span></section>
<div className="principles"><span><Sprout/>{t('Verimli üretim','Productive growing')}</span><span><ScanLine/>{t('Modern teknoloji','Modern technology')}</span><span><Leaf/>{t('Her aşamada destek','Support at every stage')}</span><span className="principles-last">{t('TOPRAĞINIZ İÇİN DAHA FAZLASI','MORE FOR YOUR LAND')} ↗</span></div>
<section id="hakkimizda" className="section about reveal"><div><p className="eyebrow">01 / {t('BİZ KİMİZ?','WHO WE ARE')}</p><h2>{t('Toprağı tanıyoruz.\nGeleceğe bakıyoruz.','We know the land.\nWe look ahead.')}</h2></div><div className="about-copy"><p>{en?c.aboutEn:c.aboutTr}</p><a className="text-link" href={en?'/en/hakkimizda':'/hakkimizda'}>{t('OKUR AGRO ile tanışın','Meet OKUR AGRO')}<ArrowUpRight/></a><div className="about-facts"><div><strong>2026</strong><span>{t('Kuruluş yılımız','Established')}</span></div><div><strong>Siirt</strong><span>{t('Köklerimizin olduğu yer','Where our roots are')}</span></div></div></div></section>
<section id="hizmetler" className="solutions section"><div className="section-heading reveal"><div><p className="eyebrow">02 / {t('ÇÖZÜMLERİMİZ','OUR SOLUTIONS')}</p><h2>{t('İhtiyacınız olan destek.\nTek bir adreste.','The support you need.\nAll in one place.')}</h2></div><p>{t('Bilgiyi, teknolojiyi ve doğru ürünü bir araya getiriyor; üretiminize değer katıyoruz.','Bringing expertise, technology and the right products together for your production.')}</p></div><div className="service-grid">{c.services.map((s,i)=>{const Icon=[Sprout,Leaf,ScanLine,Tractor,Leaf,Sprout,Wind][i%7];return <a className={'service reveal '+(s.soon?'upcoming':'')} href={`${en?'/en':''}/cozumler/${s.id}`} key={s.id}><div className="service-top">{s.image?<img src={s.image} alt=""/>:<Icon size={28} strokeWidth={1.3}/>}<span>{String(i+1).padStart(2,'0')}</span></div><div>{s.soon&&<span className="badge">{t('Yakında','Coming soon')}</span>}<h3>{en?s.en:s.tr}</h3><p>{en?s.descEn:s.descTr}</p></div><div className="service-bottom">{t('Detayları keşfedin','Explore solution')}<ArrowUpRight size={22}/></div></a>})}</div></section>
<section className="feature"><div className="feature-image"><img src="/growing-1200.webp" srcSet="/growing-600.webp 600w, /growing-1200.webp 1200w" sizes="(max-width:700px) 100vw, 50vw" width={1200} height={800} alt={t('Kontrollü yetiştirme ortamında yeşil bitkiler','Green crops in a controlled growing environment')} loading="lazy"/><span>OKUR AGRO / {t('Temsili görsel: kontrollü ortamda fide üretimi','Illustrative photo: seedlings in a controlled environment')}</span></div><div className="feature-copy reveal"><p className="eyebrow">{t('GELENEKSEL BİLGİ, MODERN YAKLAŞIM','TRADITIONAL KNOWLEDGE, MODERN THINKING')}</p><h2>{t('Üretiminize\nyeni bir alan açın.','Make room for\na new way to grow.')}</h2><p>{t('Salep ve safran gibi katma değerli ürünlerden hidroponik ve cocopeat sistemlerine kadar, üretim olanaklarınızı birlikte değerlendirelim.','From value-added crops such as salep and saffron to hydroponic and cocopeat systems, let’s explore your growing possibilities.')}</p><a className="button green" href={wa(t('üretim çözümleri','growing solutions'))} target="_blank" rel="noreferrer">{t('Üretiminizi konuşalım','Let’s talk about your crops')}<ArrowUpRight/></a></div></section>
<section id="urunler" className="section products"><div className="section-heading reveal"><div><p className="eyebrow">03 / {t('ÜRÜNLERİMİZ','OUR PRODUCTS')}</p><h2>{t('İyi üretim,\ndoğru seçimle başlar.','Good growing starts\nwith the right choices.')}</h2></div><p>{t('Ürün seçenekleri ve tedarik bilgisi için bize ulaşın. Size uygun çözümü birlikte bulalım.','Contact us for product options and supply information. Let’s find the right solution together.')}</p></div><div className="product-list">{c.products.map((s,i)=><a className="product-row reveal" key={s.id} href={wa(en?s.en:s.tr)} target="_blank" rel="noreferrer"><span className="product-index">{String(i+1).padStart(2,'0')}</span>{s.image&&<img src={s.image} alt=""/>}<h3>{en?s.en:s.tr}</h3><p>{en?s.descEn:s.descTr}</p><span className="product-cta">{s.price||t('Bilgi al','Enquire')}<ArrowUpRight/></span></a>)}</div></section>
<section id="iletisim" className="contact section reveal"><div><p className="eyebrow">04 / {t('BİRLİKTE ÜRETELİM','LET’S GROW TOGETHER')}</p><h2>{t('Bir telefonla\nbaşlayalım.','Let’s start with\na conversation.')}</h2><p>{t('Tarlanızı, fikrinizi, ihtiyacınızı anlatın.\nBir sonraki adımı birlikte planlayalım.','Tell us about your land, your ideas, your needs.\nLet’s plan your next step together.')}</p></div><div className="contact-links"><a href={`tel:+${c.phone}`}><span>{t('BİZİ ARAYIN','CALL US')}</span><strong>{c.phone==='905461166424'?'0546 116 64 24':'+'+c.phone}</strong><MoveUpRight/></a><a href={wa(t('tarım çözümleriniz','your agricultural solutions'))} target="_blank" rel="noreferrer"><span>WHATSAPP</span><strong>{t('Mesaj gönderin','Send a message')}</strong><MoveUpRight/></a><a href={`https://instagram.com/${c.instagram}`} target="_blank" rel="noreferrer"><span>INSTAGRAM</span><strong>@{c.instagram}</strong><MoveUpRight/></a></div></section>
</main>}
<footer><div className="footer-main"><a href={home}><Logo/></a><p>{t('Geleceği Topraktan Üretiyoruz.','We Grow the Future from the Soil.')}</p><span><MapPin size={17}/>{c.location}, Türkiye</span></div><nav className="footer-pages" aria-label={en?"More information":"Diğer sayfalar"}>{[["hakkimizda",t("Hakkımızda","About")],["iletisim",t("Bize ulaşın","Contact")],["sss",t("SSS","FAQ")],["hizmet-bolgeleri/siirt","Siirt"],["hizmet-bolgeleri/turkiye",t("Türkiye geneli","Across Türkiye")],["gizlilik",t("Gizlilik","Privacy")],["kullanim-kosullari",t("Kullanım koşulları","Terms")]].map(([path,label])=><a key={path} href={`${en?"/en":""}/${path}`}>{label}</a>)}</nav><div className="footer-bottom"><span>© {new Date().getFullYear()} OKUR AGRO</span><a href="/yonetim">{t('Yönetim','Administration')} ↗</a><span>{t('Siirt merkezli, Türkiye genelinde.','Based in Siirt, serving Türkiye.')}</span></div></footer><a className="floating-wa" aria-label="WhatsApp" href={wa(t('hizmetleriniz','your services'))} target="_blank" rel="noreferrer"><Phone size={20}/><span>WhatsApp</span></a>
</>;}
